before_install:
 - echo "extension=zmq.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
 - echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
 - php -m

before_script:
 - composer self-update
 - composer install

language: php
php:
 - 5.6
 - 5.5
 - 5.4
 - 5.3
matrix:
    allow_failures:
        - php: 5.6

notifications:
  irc:
      - "chat.freenode.net#alpharpc"
  email:
    on_success: change
    on_failure: change
