parameters:
  logger_client_handler_file: logs/alpharpc-client-handler.log
  logger_client_handler_level: 0

  logger_worker_handler_file: logs/alpharpc-worker-handler.log
  logger_worker_handler_level: 0

  client_handler: tcp://127.0.0.1:61002
  worker_handler: tcp://127.0.0.1:61003

  client_handler_worker_handler: ipc://ipc/alpharpc_client_handler_worker_handler.ipc
  worker_handler_status:         ipc://ipc/alpharpc_worker_status.ipc

  # This value should be less than or equal to the delay provided to the clients and worker.
  manager_delay: 1000
